### ISSUE TITLE
NEVERMIND, YOU COPIED ME!

### ISSUE THREAD

**Issue by PrinceFroggy** [chenhil/Supreme#2]
YOU COPIED ME!

**Comment by chenhil** [comment]
In what way did I copy you?

**Comment by PrinceFroggy** [comment]
I don't care if you copied, I already released the new navigation without DOM elements (webBrowser is blocked).

**Comment by chenhil** [comment]
In no way did I copy you. Learning to use htmlagilitypack was trivial and had an abundent of information online and understanding the request params for supreme was not challenging at all. If you think I copied you because I stopped updating this 2 years ago, its simply because I did his for a learning purpose. It'll be a complete waste of my time to "copy" your code to a new project when I could have cloned yours.

**Comment by PrinceFroggy** [comment]
You copied me 100%.

https://www.youtube.com/watch?v=tv7Q7u_CF0A

I had my own bot published even before April 8, 2015

**Comment by chenhil** [comment]
You're an idiot.
